// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAruGKMbeym_kBmezu1IGJDK30r3hkhU',
    appId: '1:926323434708:web:48eef4bd4718f05bf0c741',
    messagingSenderId: '926323434708',
    projectId: 'brew-notes-84b16',
    authDomain: 'brew-notes-84b16.firebaseapp.com',
    storageBucket: 'brew-notes-84b16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3wY6GJslfuLKo7VIIiStrwZcovWbQ3o',
    appId: '1:926323434708:android:6a08b4a628498768f0c741',
    messagingSenderId: '926323434708',
    projectId: 'brew-notes-84b16',
    storageBucket: 'brew-notes-84b16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5x_0FQ3MeGRF8R4u1BuAcLxgsr-Elguw',
    appId: '1:926323434708:ios:d7c68a60f8c967ddf0c741',
    messagingSenderId: '926323434708',
    projectId: 'brew-notes-84b16',
    storageBucket: 'brew-notes-84b16.firebasestorage.app',
    iosBundleId: 'areen.brewnotes.brewNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5x_0FQ3MeGRF8R4u1BuAcLxgsr-Elguw',
    appId: '1:926323434708:ios:d7c68a60f8c967ddf0c741',
    messagingSenderId: '926323434708',
    projectId: 'brew-notes-84b16',
    storageBucket: 'brew-notes-84b16.firebasestorage.app',
    iosBundleId: 'areen.brewnotes.brewNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBAruGKMbeym_kBmezu1IGJDK30r3hkhU',
    appId: '1:926323434708:web:4074ed6addf3e991f0c741',
    messagingSenderId: '926323434708',
    projectId: 'brew-notes-84b16',
    authDomain: 'brew-notes-84b16.firebaseapp.com',
    storageBucket: 'brew-notes-84b16.firebasestorage.app',
  );
}
